### ISSUE TITLE
yarn package fails with node 12.22.9

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#1108]
I have an Ubuntu system with node 12.22.9 installed, when I run yarn package I get this error:

> error @vscode/debugadapter@1.63.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.9"

If run `npm install --global node@14`, then I get the error

> error @vscode/test-electron@2.3.8: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.3"

Running `npm install --global node@16` then yarn package succeeds.

The README says Node 10 or higher should work, and CI looks like it only tests 16. What versions of node are supported?

Also, can the node version be defined in package.json or yarn.lock, or does it have to be installed outside of that?

**Comment by shanedell** [comment]
@stevedlawrence I believe this something we need to update in the README. In CI we are testing NodeJS 16 and 18. So we know those are supported, but technically newer versions above 16 should work but I am not 100% confident on that as sometimes newer releases can some things to break. For example, we test with NodeJS 18.20.1 because 18.20.2 seemed to cause things to break.
