### ISSUE TITLE
Create better build setup

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#121]
The current way we build the VSIX file, by moving the `LICENSE` and `NOTICE` files to temp files, `build/bin.NOTICE` and `build/bin.LICENSE` to `LICENSE` and `NOTICE` then moving things back is not the cleanest.

This ticket is to come up with a better way to bundle the `build/bin.NOTICE` and `build/bin.LICENSE` files inside of the VSIX as the `NOTICE` and `LICENSE` files.

- This ticket stems from this comment https://github.com/apache/daffodil-vscode/pull/117#discussion_r883590704

**Comment by Shanedell** [comment]
@stevedlawrence
Do you have any ideas for this? The only real other option I could think of was creating a script that will:

- Create a folder `build/package`
- Loop over the contents of `.vscodeignore` that start with `!`
- For each file/directory copy it into `build/package/`
- cd to `build/package`
- create VSIX
- mv VSIX from `build/package` to root
- remove `build/package`

**Comment by stevedlawrence** [comment]
Seems reasonable to me. I might suggest putting the `package` directory in `target/` or `out/` or some other directory that is already ignored and is intended for temporary build artifacts, but I don't feel strongly about it.

Also, it would be even better if all the pieces could be configured so their output location is in the package directory so you don't have to scan .vscodeignore and copy everything. For example, the download of the omega edit release could output straight to that directory. NPM/yarn seems pretty limited in its configuration though, so that might not be possible for some things, in which case copying from vscodeignore might make the most sense.

**Comment by stevedlawrence** [comment]
Sorry, I was on vacation and didn't get a chance to review the merged change.

I'm not sure the merged commit addresses my original concern in this ticket. The new code still overwrites the LICENSE/NOTICE files in the root and restores them, it just does it in a different way:

```typescript
  fs.renameSync('LICENSE', 'tmp.LICENSE')
  fs.renameSync('NOTICE', 'tmp.NOTICE')
  fs.copyFileSync('build/bin.NOTICE', 'NOTICE')
  fs.copyFileSync('build/bin.LICENSE', 'LICENSE')
  ...
  fs.rmSync('LICENSE')
  fs.rmSync('NOTICE')
  fs.renameSync('tmp.LICENSE', 'LICENSE')
  fs.renameSync('tmp.NOTICE', 'NOTICE')
```

My main concern with this ticket is that we shouldn't be overwritting the root LICENSE/NOTICE files. Similarly, the new change also executes git to undo changes, which is fragile--we really don't want the chance to automatically revert someones changes to these files if something in the build goes wrong.

I thought your suggestion of coyping things into a new build/package directory and building everything out of that seemed reasonable. Did that not work?

**Comment by Shanedell** [comment]
I think I was still working on that, did this as an in between but will look into getting that fully done now.
