### ISSUE TITLE
Suppress platform conditionals

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#301]
Definitely make it a goal to use a library that suppresses all these platform conditionalizations before they proliferate. 

As people add new tests they should NOT copy this. 

We didn't do that soon enough in the daffodil-cli test rig, and the code-volume legacy of these sort of trivial conditionalization literring that test code is way too high.

_Originally posted by @mbeckerle in https://github.com/apache/daffodil-vscode/pull/240#discussion_r975803640_

**Comment by Shanedell** [comment]
@mbeckerle I am not sure if this can be done as with running scripts on different OSes we will need to know if its windows so it knows the proper script to use. From looking around I could not find any node packages that would allow for us to remove these checks. The closes thing was a package called `run-script-os` but that is for adding things to `package.json` not helping with doing inside of TS code. What are your thoughts?

**Comment by stevedlawrence** [comment]
An alternative is to create a small library of test utility functions that contain the os specific logic.

For example, in the Daffodil CLI integration tests we have a `devNull` function that returns `/dev/null` on linux and `NUL` on windows. Any time a test needs to get the path to the null device, we can call this function and the test itself doesn't have to contain the os.platform logic. You could create similar functions for getting the daffodil path with .bat vs no .bat, etc.

It looks like you already have a `killProcess` that does this. Adding more functions for os specific logic should help to avoid the issues we had with the Daffodil CLI tests.

**Comment by Shanedell** [comment]
Oh okay that makes sense, so two options

Option 1:

Try to make a general function that does an os check then returns the approiate option
```typescript
function checkOS(windowOption: string, macLinuxOption) {
  return os.platform() == 'win32' ? windowsOption : macLinuxOption
}
```

Option 2:

Split code into separate functions, similar to `killPrcoess`

```typescript
function stopDebugger() {
  // Stop debugger if running
  if (os.platform() === 'win32') {
    // Windows stop debugger if already running
    child_process.execSync(
      'tskill java 2>nul 1>nul || echo "Java not running"'
    )
  } else {
    // Linux/Mac stop debugger if already running and make sure script is executable
    child_process.exec(
      "kill -9 $(ps -ef | grep 'daffodil' | grep 'jar' | awk '{ print $2 }') || return 0"
    ) // ensure debugger server not running and
  }
}
```

So with option one we could do
```typescript
child_process.exec(
  checkOS(
    'tskill java 2>nul 1>nul || echo "Java not running"',
    "kill -9 $(ps -ef | grep 'daffodil' | grep 'jar' | awk '{ print $2 }') || return 0"
  )
)
```

instead splitting into a method in option 2. Which would be preferred or a combination of both?

**Comment by stevedlawrence** [comment]
Personally, I find option 2 much more legible and is much more likely to reduce duplication if multiple tests need to stop a debugger.

I'm not sure if it's possible in typescript, but in the Daffodil CLI, we do something that looks something that might look like this for debugger tests:

```
runDebugger(...) { debugger =>
   // test logic that uses debugger
}
```
The stuff in the brackets is an anonymous function that accepts a `debugger` as a parameter. So the `runDebugger` does whatever initialization is needed to create a debugger (which might be os specific), passes that "debugger" instance to the anonymous function to actually do real testing logic, and then when that anon function returns, the runDebugger does whatever cleanup is needed (which might also be os specific). This way all the os specific startup/shutdown logic (e.g. find the .bat/no .bat file, kill a process) can be in the `runDebugger` utility, and then the debugger logic in the anonymous function doesn't have to do any os specific stuff or even think about cleanup--it's just all handled by the `runDebugger` function.

The CLI Integration test utilities has a `runCLI` function that does exactly what I describe, though it's a bit complicated because the initialization logic is fairly complex to support threads vs processes and set up our testing infrastructure.

https://github.com/apache/daffodil/blob/main/daffodil-cli/src/it/scala/org/apache/daffodil/CLI/Util.scala#L185

This approach might be overkill for the vscode tests though, it's not clear to me how often you need this kind of pattern.
