### ISSUE TITLE
Click upon seperator space in Logical window

### ISSUE THREAD

**Issue by lrbarber** [apache/daffodil-vscode#568]
It is possible to click on the space inserted between characters in the Logical window. This results in an unmoved and empty Edit widget and if you were previously in the Physical window, the widget remains there...
![image](https://user-images.githubusercontent.com/72564532/230087785-616e1e35-16ff-4c7e-957c-67f93c322910.png)
You can see the outline shows that the Logical window was clicked in, but the Edit widget is still in the Physical, but is now empty.

**Comment by lrbarber** [comment]
This can also occur when clicking in the Physical window.

**Comment by lrbarber** [comment]
Interestingly, the Data View **does** update (offset & values)

**Comment by stricklandrbls** [comment]
@lrbarber are you on the latest branch? That Latin-1 character standin is not what is currently implemented as the standin.

**Your branch's standin**
![image](https://user-images.githubusercontent.com/30351915/230124323-20e3b0ec-4d80-4049-8af2-a333ffc62368.png)
_should_ look like 
![image](https://user-images.githubusercontent.com/30351915/230124545-8ca20564-9702-4efb-8c82-8f50c1291c1f.png)

I see that the empty spaces are actually `0x20` or an ascii space character but I'm not sure why your standin looks different unless it's OS / font related.

**Comment by lrbarber** [comment]
I update yesterday morning. It used to show a diamond so I thought this was the new standin. I'm running on Rocky 9.

**Comment by lrbarber** [comment]
With single clicks, the Data View window seems to work correctly -- so the algorithm works, but somehow that information doesn't get fed to the ephemeral window.

**Comment by stricklandrbls** [comment]
So the Data View is based off the cursor position of where the user clicks and registers a start index for a selection. This is done prior to the whitespace detection alignment so the Data View will serve information based on that info.

I believe that the whitespace alignment is eventually calculating a null value and that's why no data is being populated into the edit byte window's input field. Fixing this would require altering how the whitespace determination takes place.

I'll continue to look into this for a solution.
