### ISSUE TITLE
Use daffodil-tdml library

### ISSUE THREAD

**Issue by michael-hoke** [apache/daffodil-vscode#594]
Use official TDML library from https://mvnrepository.com/artifact/org.apache.daffodil/daffodil-tdml and remove scalaxjc.

**Comment by arosien** [comment]
I think the daffodil-tdml library isn't really for programmatic manipulation of test cases. It is more of an interpreter of the data that executes the test cases.

Instead of using those classes, we can use the ones defined in the XSD files that we generate Scala data structures for, via JAXB, and then define extension methods to manipulate them (append test case, etc.). We can then [marshal](https://www.baeldung.com/jaxb#marshalling---converting-java-object-to-xml) these back to XML to pass to the daffodil-tdml `TDMLRunner` for execution.

**Comment by nlewis05** [comment]
Work was being completed under this PR on the apache-daffodil repo https://github.com/apache/daffodil/pull/1057

**Comment by hdalsania** [comment]
Once the https://github.com/apache/daffodil/pull/1057 merged on DFDL side, We need to import the latest DFDL version and then remove scalaxjc with official TDML library from https://mvnrepository.com/artifact/org.apache.daffodil/daffodil-tdml. This library will only be available in maven after DFDL cut release with above PR.

**Comment by arosien** [comment]
Copied from https://github.com/apache/daffodil/pull/1057#issuecomment-2151100868:

Closing for multiple reasons:
- TDML XML object mapping support isn't used, or can be avoided, in downstream Scala projects like [daffodil-vscode](https://github.com/apache/daffodil-vscode). See [above](https://github.com/apache/daffodil/pull/1057#discussion_r1484667731) for more context.
- The original JAXB solution was deemed to have too particular build configuration given differences between JVM versions, so scalaxb was chosen instead. But since JVM 21 was introduced it also appears to have JVM version dependent build configuration, which is slightly annoying. It's not a blocker, however.
- Given the oddities of XML object binding, the need for an alternative was proposed [above](https://github.com/apache/daffodil/pull/1057#discussion_r1484660294), say, JSON, which may fit more downstream languages like Scala and Typescript.
