### ISSUE TITLE
not all buttons are being re-expanded after being shrunk

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#761]
In the image below, the save buttons and the apply button in the content controls field set are still icon only, though the other buttons have expanded to include their labels.

<img width="1894" alt="Screenshot 2023-08-10 at 11 25 37 AM" src="https://github.com/apache/daffodil-vscode/assets/2205472/c33c3b77-b791-4901-b4b6-4e3c14012d78">

**Comment by stricklandrbls** [comment]
I'm on ctc-oss/main and am not seeing this issue. I'm not entirely sure what else would cause this since the `Button` component collapsing is derived from the `document.body.clientWidth`.

![Peek 2023-08-10 11-33](https://github.com/apache/daffodil-vscode/assets/30351915/a4937032-3227-4903-abb4-9840bd030ca0)

**Comment by scholarsmate** [comment]
@stricklandrbls, it happens when the buttons are hidden while the expansion takes place.  If the Content Controls or the Save buttons are not visible at the time of the expansion, they don't get expanded when they are visible again.

**Comment by stricklandrbls** [comment]
Like in the image below? I'm not sure how the `Apply` button can be hidden **while** the expansion takes place.

![Peek 2023-08-11 10-42](https://github.com/apache/daffodil-vscode/assets/30351915/8974ad11-2a2a-488e-bad1-182ad9e6b692)
