### ISSUE TITLE
Ability to navigate to a certain relative byte index

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#799]
Move over a certain number of bytes over, rather than seek to offset

ex:
type 172 and then hit go and it will move the cursor that many bytes over (positive for seeking forward and negative for seeking backward)

**Comment by scholarsmate** [comment]
We need to distinguish between absolute offsets and relative ones (go this many bytes forward or backward).  If the desire is to move 172 bytes forward, use +172 since 172 would indicate an absolute offset.  Of course -172 would move 172 bytes backward.  The current byte offset probably ought to have some visual indicator in the physical and logical viewports.

**Comment by stricklandrbls** [comment]
@scholarsmate @nlewis05 - That branch should be ready for PR, how do we want to handle reviews till v1.3.1 is released?

**Comment by nlewis05** [comment]
Probably best to leave it as a PR and wait, I don't think 1.3.1 review will take much longer and last time when we tried to implement an intermediary "development" branch to merge future changes into before going into main, people either didn't use it and we just had to merge each individual PR anyways, but I know that "main" being locked during a release is frustrating and we should look into how other apache projects handle this issue.
