### ISSUE TITLE
Debugger Restart DataEditor tracking/reopen failures

### ISSUE THREAD

**Issue by lrbarber** [apache/daffodil-vscode#932]
Stepping through a parse, then use the Restart button (Ctrl+Shift+F5), causes a new DataEditor tab to open -- the new instance triggers error messages "**Failed to create Session...**" & "**Failed to create viewport...**". 
The original tab loses the location tracking highlight and the new one just shows filename, 0B size, and empty Physical/Logical windows.

**Comment by hdalsania** [comment]
This behavior is happening in Rocky 9 Linux platform as well.

**Comment by lrbarber** [comment]
On Linux, if you close the DataEditor tab, then click Restart, it seems to work fine.
On Windows, if you close the DataEditor tab, then click Restart, a new tab opens and it loads the file, but the location tracker doesn't show up.

**Comment by stricklandrbls** [comment]
@lrbarber @hdalsania I currently have the Data Editor disposing and re-initializing when the debugger is restarted but a fix for this is currently blocked, on Windows systems, due to this issue: https://github.com/ctc-oss/omega-edit/issues/858.

When I get some more time I will try to look into a fix for that issue or determine a better Data Editor 'restart'.

**Comment by stricklandrbls** [comment]
@lrbarber @hdalsania 
I've merged in a commit (https://github.com/ctc-oss/omega-edit/pull/860) to the Omega Edit repo and will start to work towards testing the extension on Windows to see if this commit resolves the inability to start & restart the data editor.

When those tests work I will be able to put a PR up for the branch I have for managing the data editor when the debugger restarts / stops.

**Comment by stricklandrbls** [comment]
My original solution would close both this issue and #898 . Unfortunately, this issue will require a must more in depth revision due to the data editor webview & omega edit server communication / heartbeat. 

The branch I currently have for this issue will successfully shut down and restart an instance of the data editor, upon debug session restart, but the DFDLRuntime data messages that are sent to the data editor are not being received anymore.
